(function(){function a(){f||(f=!0,c[d].load[e]("firstScrollTime"))}var c=window,d="jstiming",e="tick",b=function(a){this.t={};this.tick=function(a,b,c){c=void 0!=c?c:(new Date).getTime();this.t[a]=[c,b]};this[e]("start",null,a)},l=new b;c.jstiming={Timer:b,load:l};if(c.performance&&c.performance.timing){var b=c.performance.timing,h=c[d].load,k=b.navigationStart,b=b.responseStart;0<k&&b>=k&&(h[e]("_wtsrt",void 0,k),h[e]("wtsrt_","_wtsrt",b),h[e]("tbsd_","wtsrt_"))}try{b=null,c.chrome&&c.chrome.csi&&
(b=Math.floor(c.chrome.csi().pageT),h&&0<k&&(h[e]("_tbnd",void 0,c.chrome.csi().startE),h[e]("tbnd_","_tbnd",k))),null==b&&c.gtbExternal&&(b=c.gtbExternal.pageT()),null==b&&c.external&&(b=c.external.pageT,h&&0<k&&(h[e]("_tbnd",void 0,c.external.startE),h[e]("tbnd_","_tbnd",k))),b&&(c[d].pt=b)}catch(g){}c.tickAboveFold=function(a){var b=0;if(a.offsetParent){do b+=a.offsetTop;while(a=a.offsetParent)}750>=b&&c[d].load[e]("aft")};var f=!1;c.addEventListener?c.addEventListener("scroll",a,!1):c.attachEvent("onscroll",
a)})();(function(a,c,d){a.fn.tinyNav=function(e){var b=a.extend({active:"selected",header:"",label:""},e);return this.each(function(){d++;var e=a(this),h="tinynav"+d,k=".l_"+h,g=a("<select/>").attr("id",h).addClass("tinynav "+h);if(e.is("ul,ol")){""!==b.header&&g.append(a("<option/>").text(b.header));var f="";e.addClass("l_"+h).find("a").each(function(){f+='<option value="'+a(this).attr("href")+'">';var b;for(b=0;b<a(this).parents("ul, ol").length-1;b++)f+="- ";f+=a(this).text()+"</option>"});g.append(f);
b.header||g.find(":eq("+a(k+" li").index(a(k+" li."+b.active))+")").attr("selected",!0);g.change(function(){c.location.href=a(this).val()});a(k).after(g);b.label&&g.before(a("<label/>").attr("for",h).addClass("tinynav_label "+h+"_label").append(b.label))}})}})(jQuery,this,0);function showpageCount(a){for(var c=home_page_url,d=[],e=1,b=1,l=0,h=0,k=0,g="",f="",p="",q=0,m;m=a.feed.entry[q];q++){var r=m.published.$t.substring(0,19)+m.published.$t.substring(23,29);timestamp=encodeURIComponent(r);m=m.title.$t;""==m||0!=l&&l%pageCount!=pageCount-1||(-1!=c.indexOf(timestamp)&&(e=b),""!=m&&b++,d[d.length]="/search?updated-max="+timestamp+"&max-results="+pageCount);l++}for(a=0;a<d.length;a++)a>=e-displayPageNum-1&&a<e+displayPageNum&&(0==h&&a==e-2&&(f=2==e?'<span class="showpage"><a href="/">'+
upPageWord+"</a></span>":'<span class="showpage"><a href="'+d[a]+'">'+upPageWord+"</a></span>",h++),g=a==e-1?g+('<span class="showpagePoint">'+e+"</span>"):0==a?g+'<span class="showpageNum"><a href="/">1</a></span>':g+('<span class="showpageNum"><a href="'+d[a]+'">'+(a+1)+"</a></span>"),0==k&&a==e&&(p='<span class="showpage"> <a href="'+d[a]+'">'+downPageWord+"</a></span>",k++));1<e&&(g=""+f+" "+g+" ");g='<div class="showpageArea"><span style="COLOR: #000;" class="showpageOf"> Pages ('+(b-1)+")</span>"+
g;e<b-1&&(g+=p);1==b&&b++;g+="</div>";d=document.getElementsByName("pageArea");e=document.getElementById("blog-pager");2>=b&&(g="");for(a=0;a<d.length;a++)d[a].innerHTML=g;d&&0<d.length&&(g="");e&&(e.innerHTML=g)}
function showpageCount2(a){for(var c=home_page_url,d=[],e=-1!=c.indexOf("/search/label/")?c.substr(c.indexOf("/search/label/")+14,c.length):"",e=-1!=e.indexOf("?")?e.substr(0,e.indexOf("?")):e,b=1,l=1,h=0,k=0,g=0,f="",p="",q="",m='<span class="showpageNum"><a href="/search/label/'+e+"?&max-results="+pageCount+'">',c=home_page_url,r=0,n;n=a.feed.entry[r];r++){var s=n.published.$t.substring(0,19)+n.published.$t.substring(23,29);timestamp=encodeURIComponent(s);n=n.title.$t;""==n||0!=h&&h%pageCount!=
pageCount-1||(-1!=c.indexOf(timestamp)&&(b=l),""!=n&&l++,d[d.length]="/search/label/"+e+"?updated-max="+timestamp+"&max-results="+pageCount);h++}for(a=0;a<d.length;a++)a>=b-displayPageNum-1&&a<b+displayPageNum&&(0==k&&a==b-2&&(p=2==b?m+upPageWord+"</a></span>":'<span class="showpage"><a href="'+d[a]+'">'+upPageWord+"</a></span>",k++),f=a==b-1?f+('<span class="showpagePoint">'+b+"</span>"):0==a?m+"1</a></span>":f+('<span class="showpageNum"><a href="'+d[a]+'">'+(a+1)+"</a></span>"),0==g&&a==b&&(q=
'<span class="showpage"> <a href="'+d[a]+'">'+downPageWord+"</a></span>",g++));1<b&&(f=""+p+" "+f+" ");f='<div class="showpageArea"><span style="COLOR: #000;" class="showpageOf"> Pages ('+(l-1)+")</span>"+f;b<l-1&&(f+=q);1==l&&l++;f+="</div>";d=document.getElementsByName("pageArea");b=document.getElementById("blog-pager");2>=l&&(f="");for(a=0;a<d.length;a++)d[a].innerHTML=f;d&&0<d.length&&(f="");b&&(b.innerHTML=f)}var home_page_url=location.href,thisUrl=home_page_url;
if(-1!=thisUrl.indexOf("/search/label/"))var lblname1=-1!=thisUrl.indexOf("?updated-max")?thisUrl.substring(thisUrl.indexOf("/search/label/")+14,thisUrl.indexOf("?updated-max")):thisUrl.substring(thisUrl.indexOf("/search/label/")+14,thisUrl.indexOf("?&max"));var home_page="/";
-1==thisUrl.indexOf("?q=")&&(-1==thisUrl.indexOf("/search/label/")?document.write('<script src="'+home_page+'feeds/posts/summary?alt=json-in-script&callback=showpageCount&max-results=99999" >\x3c/script>'):document.write('<script src="'+home_page+"feeds/posts/full/-/"+lblname1+'?alt=json-in-script&callback=showpageCount2&max-results=99999" >\x3c/script>'));(function(a,c){function d(){var a=s.elements;return"string"==typeof a?a.split(" "):a}function e(a){var b=r[a[q]];b||(b={},m++,a[q]=m,r[m]=b);return b}function b(a,b,d){b||(b=c);if(n)return b.createElement(a);d||(d=e(b));b=d.cache[a]?d.cache[a].cloneNode():f.test(a)?(d.cache[a]=d.createElem(a)).cloneNode():d.createElem(a);return b.canHaveChildren&&!g.test(a)?d.frag.appendChild(b):b}function l(a,c){c.cache||(c.cache={},c.createElem=a.createElement,c.createFrag=a.createDocumentFragment,c.frag=c.createFrag());
a.createElement=function(d){return s.shivMethods?b(d,a,c):c.createElem(d)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+d().join().replace(/\w+/g,function(a){c.createElem(a);c.frag.createElement(a);return'c("'+a+'")'})+");return n}")(s,c.frag)}function h(a){a||(a=c);var b=e(a);if(s.shivCSS&&!p&&!b.hasCSS){var d,f=a;d=f.createElement("p");f=f.getElementsByTagName("head")[0]||f.documentElement;d.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}</style>";
d=f.insertBefore(d.lastChild,f.firstChild);b.hasCSS=!!d}n||l(a,b);return a}var k=a.html5||{},g=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,f=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,p,q="_html5shiv",m=0,r={},n;(function(){try{var a=c.createElement("a");a.innerHTML="<xyz></xyz>";p="hidden"in a;var b;if(!(b=1==a.childNodes.length)){c.createElement("a");var d=c.createDocumentFragment();b="undefined"==typeof d.cloneNode||
"undefined"==typeof d.createDocumentFragment||"undefined"==typeof d.createElement}n=b}catch(e){n=p=!0}})();var s={elements:k.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup main mark meter nav output progress section summary time video",version:"3.6.2pre",shivCSS:!1!==k.shivCSS,supportsUnknownElements:n,shivMethods:!1!==k.shivMethods,type:"default",shivDocument:h,createElement:b,createDocumentFragment:function(a,b){a||(a=c);if(n)return a.createDocumentFragment();
b=b||e(a);for(var f=b.frag.cloneNode(),g=0,h=d(),k=h.length;g<k;g++)f.createElement(h[g]);return f}};a.html5=s;h(c)})(this,document);